# Generated by Django 3.1.7 on 2021-04-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='img',
            field=models.ImageField(default='huvai', upload_to='images'),
            preserve_default=False,
        ),
    ]
